import { User } from '../types/users.type';

export const userData1: User[] = [
  {
    id: 1,
    firstName: 'Aarav',
    lastName: 'Sharma',
    gender: 'Male',
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
    phone: '+91-9876543210',
    email: 'aarav.sharma@example.com',
    streetAddress: '123 MG Road',
    city: 'Bangalore',
    state: 'Karnataka',
  },
  {
    id: 2,
    firstName: 'Priya',
    lastName: 'Patel',
    gender: 'Female',
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    phone: '+91-9876543211',
    email: 'priya.patel@example.com',
    streetAddress: '456 Link Road',
    city: 'Mumbai',
    state: 'Maharashtra',
  },
  {
    id: 3,
    firstName: 'Rohan',
    lastName: 'Gupta',
    gender: 'Male',
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    phone: '+91-9876543212',
    email: 'rohan.gupta@example.com',
    streetAddress: '789 Park Street',
    city: 'Kolkata',
    state: 'West Bengal',
  },
  {
    id: 4,
    firstName: 'Ananya',
    lastName: 'Desai',
    gender: 'Female',
    photo: 'https://randomuser.me/api/portraits/women/4.jpg',
    phone: '+91-9876543213',
    email: 'ananya.desai@example.com',
    streetAddress: '101 SG Highway',
    city: 'Ahmedabad',
    state: 'Gujarat',
  },
  {
    id: 5,
    firstName: 'Vikram',
    lastName: 'Singh',
    gender: 'Male',
    photo: 'https://randomuser.me/api/portraits/men/5.jpg',
    phone: '+91-9876543214',
    email: 'vikram.singh@example.com',
    streetAddress: '202 Mall Road',
    city: 'Shimla',
    state: 'Himachal Pradesh',
  },
  {
    id: 6,
    firstName: 'Neha',
    lastName: 'Reddy',
    gender: 'Female',
    photo: 'https://randomuser.me/api/portraits/women/6.jpg',
    phone: '+91-9876543215',
    email: 'neha.reddy@example.com',
    streetAddress: '303 Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
  },
  {
    id: 7,
    firstName: 'Aditya',
    lastName: 'Verma',
    gender: 'Male',
    photo: 'https://randomuser.me/api/portraits/men/7.jpg',
    phone: '+91-9876543216',
    email: 'aditya.verma@example.com',
    streetAddress: '404 Civil Lines',
    city: 'Jaipur',
    state: 'Rajasthan',
  },
  {
    id: 8,
    firstName: 'Kavya',
    lastName: 'Nair',
    gender: 'Female',
    photo: 'https://randomuser.me/api/portraits/women/8.jpg',
    phone: '+91-9876543217',
    email: 'kavya.nair@example.com',
    streetAddress: '505 Marine Drive',
    city: 'Kochi',
    state: 'Kerala',
  },
  {
    id: 9,
    firstName: 'Arjun',
    lastName: 'Kumar',
    gender: 'Male',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
    phone: '+91-9876543218',
    email: 'arjun.kumar@example.com',
    streetAddress: '606 Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
  },
  {
    id: 10,
    firstName: 'Sanya',
    lastName: 'Iyer',
    gender: 'Female',
    photo: 'https://randomuser.me/api/portraits/women/10.jpg',
    phone: '+91-9876543219',
    email: 'sanya.iyer@example.com',
    streetAddress: '707 Anna Salai',
    city: 'Chennai',
    state: 'Tamil Nadu',
  },
];
